### ISSUE TITLE
Pipeline parameters are not passed to ADF pipeline

### ISSUE THREAD

**Issue by LianaN** [liprec/vsts-publish-adf#50]
I am triggering the execution of ADF pipeline from Azure DevOps as follows:

```
    steps:
    - task: liprec.vsts-publish-adf.trigger-adf-pipeline.trigger-adf-pipeline@2
      displayName: 'Trigger ADF Training pipeline'
      inputs:
        azureSubscription: aml-workspace-serviceconnection
        ResourceGroupName: ms-mlops-rg
        DatafactoryName: adf-workspace-mlops
        PipelineFilter: Train_Pipeline
        PipelineParameter: azdo-variables-train.json
```

The content of `azdo-variables-train.json`:

```
{
    "pipeline_type": "Train",
    "days_qty": "10",
    "receiver": "myname@gmail.com"
}
```

In ADF , I created empty parameters for the pipeline `Train_Pipeline`. These parameters have the same names: `pipeline_type`, `days_qty` and `receiver`. 

![image](https://user-images.githubusercontent.com/11301976/74595506-5c9bcf00-5042-11ea-94d8-b262d3072f2a.png)

I expect that the values from `azdo-variables-train.json` will be passed to these parameters. However, it does not happen.

If, however, I define the values of parameters of the pipeline `Train_Pipeline` inside ADF, then obviously everything works fine.

**Comment by liprec** [comment]
Currently the trigger parameter can either be a variable or a fixed JSON snippet. A file is not (yet) supported, but a good addition to add to the next version.

**Comment by liprec** [comment]
I have just uploaded a new version (V2.2.0) which contains this enhancement.

**Comment by LianaN** [comment]
Dear Jan, could you please confirm that the new way to pass JSON file is the following?

```
    steps:
    - task: liprec.vsts-publish-adf.trigger-adf-pipeline.trigger-adf-pipeline@2
      displayName: 'Trigger ADF Training pipeline'
      inputs:
        azureSubscription: aml-workspace-serviceconnection
        ResourceGroupName: ms-mlops-rg
        DatafactoryName: adf-workspace-mlops
        PipelineFilter: Train_Pipeline
        PipelineParameterPath: azdo-variables-train.json
```
