### ISSUE TITLE
Cannot execute pipelines

### ISSUE THREAD

**Issue by LianaN** [liprec/vsts-publish-adf#51]
Dear Jan,

Could you please confirm that the triggering of pipelines was not updated in the last version 2.2, and it works as earlier?
The problem is that starting from v2.2 I cannot trigger DataFactory pipelines using my code (see below). I do not get any error though. Just DataFactory pipelines are not executed.

![image](https://user-images.githubusercontent.com/11301976/75018060-916ab480-548e-11ea-8710-d9609ac3a8be.png)
 
Please see the triggering code below.
Please notice that I can stil execute the pipelines directly from DataFactory.

Could you please point me to a possible reason of this issue?

Thanks. 

```
  jobs:

  - job: "Training"
    displayName: "Training"

    steps:
    - task: liprec.vsts-publish-adf.trigger-adf-pipeline.trigger-adf-pipeline@2
      displayName: 'Trigger ADF Training pipeline'
      inputs:
        azureSubscription: aml-workspace-serviceconnection
        ResourceGroupName: dev-ml-rg
        DatafactoryName: dev-adf-ws
        PipelineFilter: BA_Train_Pipeline
        PipelineParameterType: Path
        PipelineParameterPath: azdo-variables-train.json
```
