### ISSUE TITLE
Azure Data Factory Delete Items removes Linked Services

### ISSUE THREAD

**Issue by kvnkho** [liprec/vsts-publish-adf#53]
Hi,

I used the Azure Data Factory Delete Items task with Azure Devops to copy an Azure Data Factory from one environment to another. My intention is to delete triggers but not linked services. Below is the YAML configuration of the task:

```
steps:
- task: liprec.vsts-publish-adf.delete-adf-items.delete-adf-items@2
  displayName: 'Delete items from xxxxxxxxxxx'
  inputs:
    azureSubscription: 'XXXXXXXXX'
    ResourceGroupName: XXXXXXXXX
    DatafactoryName: XXXXXXXXX
    TriggerFilter: '*'

```

Even though I left LinkedServices blank, it seems to be deleting all of them. When I provide a value to the LinkedServices as the following:

`    ServiceFilter: TESTINGTESTING`

it works as expected and does not delete the said LinkedServices

My Task Version is 2.* (can't find if 2.0 or 2.2)

Thanks for the help!
