### ISSUE TITLE
I have 5 Triggers , Where i want to start 2 triggers. How to do that using TriggerFilter:

### ISSUE THREAD

**Issue by kumarro2** [liprec/vsts-publish-adf#68]
- task: liprec.vsts-publish-adf.toggle-adf-trigger.toggle-adf-trigger@2       
- displayName: 'Toggle trigger(s) in $(deploymentDataFactoryName)(start)'      
-  inputs:         azureSubscription: Development         
- ResourceGroupName: $(deploymentResourceGroupName)         
- DatafactoryName: $(deploymentDataFactoryName)        
-  TriggerFilter: '*'         
- TriggerStatus: start

As per above Code, How i can Start 2 Triggers out of 5

**Comment by kumarro2** [comment]
can someone please help me to resolve this issue.

**Comment by liprec** [comment]
The latest version of the task supports regular expressions as input for the `TriggerFilter` filter. So you need to provide a correct regex that only is `true` for the required triggers.

**Comment by kumarro2** [comment]
Thanks Jan, Can you please provide me the latest version of the task and also give some example to enable 2 triggers as per above ask.

**Comment by kumarro2** [comment]
Thanks Jan, Can you please provide me the latest version of the task and also give some example to enable 2 triggers as per above ask.

**Comment by devdllgit** [comment]
Hi @kumarro2, I had a similar issue recently and solved it as @liprec suggested. I had to build a regular expression that fits the triggers I wanted to stop.

For instance, in your case, you have 5 triggers: trigger1, trigger2, trigger3, trigger4, and trigger5. Of those, let's say you want to stop trigger2 and trigger5. 

You can use the following snippets to toggle your triggers:

For stopping triggers:


```
- task: toggle-adf-trigger@2
  displayName: "Stop ADF triggers after deploying artifacts"
  inputs:
    azureSubscription: yourAzureSubscription
    ResourceGroupName: yourResourceGroupName
    DatafactoryName: yourDatafactoryName
    TriggerFilter: '^(trigger2|trigger5)$'
    TriggerStatus: 'stop'
```

For starting triggers:

```
- task: toggle-adf-trigger@2
  displayName: "Start ADF triggers after deploying artifacts"
  inputs:
    azureSubscription: yourAzureSubscription
    ResourceGroupName: yourResourceGroupName
    DatafactoryName: yourDatafactoryName
    TriggerFilter: '^(trigger1|trigger3|trigger4)$'
    TriggerStatus: 'start'
```
